spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://agt-shop-db.caczui35tf6a.eu-central-1.rds.amazonaws.com:5432/product_db
    username: postgres
    password: rootroot
  jpa:
#    hibernate:
#      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              drop-target: generated/ddl/${spring.application.name}/drop-scripts.sql
#              create-target: generated/ddl/${spring.application.name}/create-scripts.sql
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
  servlet:
    context-path: /api/product-service

