server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers
          uri: http://localhost:8090
          predicates:
            - Path=/api/customers/**
