spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://agt-shop-db.caczui35tf6a.eu-central-1.rds.amazonaws.com:5432/order_db
    username: postgres
    password: rootroot
  jpa:
#    hibernate:
#      ddl-auto: validate
    database-platform:
      show-sql: true
#    properties:
#     javax:
#      persistence:
#       schema-generation:
#        scripts:
#         action: drop-and-create
#         drop-target: generated/ddl/${spring.application.name}/drop-scripts.sql
#         create-target: generated/ddl/${spring.application.name}/create-scripts.sql
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
  servlet:
    context-path: /api/order-service





