spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://agt-shop-db.caczui35tf6a.eu-central-1.rds.amazonaws.com:5432/customer_db
    username: postgres
    password: rootroot
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: create

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
  servlet:
    context-path: /api/customer-service




