spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: customer-service
          uri: lb://customer-service  # Rote da erişmek istediğim yer contex path -> http://localhost:[random port]/api/customer-service/customers
          predicates:
            - Path= /api/customer-service/customers/**  #Bana gelen istekte -> http://localhost:8080/api/customer-service/customers

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/product-service/products/**  #Bana gelen istekte -> http://localhost:8080/api/customer-service/customers

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path= /api/order-service/orders/**  #Bana gelen istekte -> http://localhost:8080/api/customer-service/customers

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080

