spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path= /api/customer-service/**
          filters:
            - RewritePath=/api/customer-service/v1/(?<segment>.*), /api/customer-service/$\{segment}

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/product-service/**
          filters:
            - RewritePath=/api/product-service/v1/(?<segment>.*), /api/product-service/$\{segment}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path= /api/order-service/**
          filters:
            - RewritePath=/api/order-service/v1/(?<segment>.*), /api/order-service/$\{segment}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080

